# Generated by Django 2.0.5 on 2018-05-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontractprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_personal.EmployeePersonalProfile', verbose_name='employee'),
        ),
    ]
