# Generated by Django 2.0.5 on 2018-05-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('HO', 'Holiday'), ('TB', 'Time back'), ('SS', 'Shift swap'), ('OV', 'Overtime')], default='SS', max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_contract.EmployeeContractProfile', verbose_name='employee_profile')),
            ],
        ),
    ]
