name: scheduleapp
channels:
- conda-forge
dependencies:
  - python=3.6
  - psycopg2=2.7.4
  - uwsgi=2.0.15
  - pip:
    - django==2.0.5
    - djangorestframework==3.8.2
    - flake8==3.5.0
    - django-cors-headers==2.2.0
    - django-countries==5.3
    - djangorestframework-simplejwt==3.2.3
#    - django-extensions==2.0.7
    - Pillow==5.1.0
    - coverage==4.5.1
    - coreapi==2.3.3
