# Generated by Django 2.0.5 on 2018-05-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availabilty', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request', verbose_name='request')),
            ],
        ),
    ]
