# Generated by Django 2.0.5 on 2018-05-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_personal', '0002_remove_employeepersonalprofile_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalprofile',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
