# Generated by Django 2.0.5 on 2018-05-21 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_personal', '0003_employeepersonalprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalprofile',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
